(() => {
'use strict';
const API=window.TRIP_PLANNER_CONFIG?.apiUrl||localStorage.getItem('travel_api_url')||'';
const CURRENCY_CATALOG=[
  {code:'TWD',name:'新台幣',symbol:'NT$',decimalPlaces:0,aliases:['台幣']},
  {code:'JPY',name:'日圓',symbol:'¥',decimalPlaces:0,aliases:['日幣']},
  {code:'KRW',name:'韓幣',symbol:'₩',decimalPlaces:0,aliases:['韓元']},
  {code:'USD',name:'美元',symbol:'US$',decimalPlaces:2,aliases:['美金']},
  {code:'EUR',name:'歐元',symbol:'€',decimalPlaces:2,aliases:[]},
  {code:'CNY',name:'人民幣',symbol:'CN¥',decimalPlaces:2,aliases:['人民幣元']},
  {code:'HKD',name:'港幣',symbol:'HK$',decimalPlaces:2,aliases:[]},
  {code:'THB',name:'泰銖',symbol:'฿',decimalPlaces:2,aliases:['泰幣']},
  {code:'GBP',name:'英鎊',symbol:'£',decimalPlaces:2,aliases:[]},
  {code:'AUD',name:'澳幣',symbol:'A$',decimalPlaces:2,aliases:['澳元']},
  {code:'CAD',name:'加幣',symbol:'C$',decimalPlaces:2,aliases:['加元']},
  {code:'SGD',name:'新加坡幣',symbol:'S$',decimalPlaces:2,aliases:['新幣']},
  {code:'VND',name:'越南盾',symbol:'₫',decimalPlaces:0,aliases:['越南幣']},
  {code:'PHP',name:'菲律賓披索',symbol:'₱',decimalPlaces:2,aliases:['披索']},
  {code:'MYR',name:'馬來西亞令吉',symbol:'RM',decimalPlaces:2,aliases:['馬幣']},
  {code:'IDR',name:'印尼盾',symbol:'Rp',decimalPlaces:0,aliases:['印尼幣']}
];
const INITIAL_QUERY=new URLSearchParams(location.search),INITIAL_TAB=INITIAL_QUERY.get('tab');
const S={page:'home',trip:null,code:INITIAL_QUERY.get('id'),user:'',tab:['wishlist','itinerary','expenses','settlement'].includes(INITIAL_TAB)?INITIAL_TAB:'wishlist',itineraryDate:/^\d{4}-\d{2}-\d{2}$/.test(INITIAL_QUERY.get('date')||'')?INITIAL_QUERY.get('date'):'',itineraryQuery:'',expenseQuery:'',settlementCurrency:'',draftMembers:[],draftCurrencies:[{code:'TWD',name:'新台幣',symbol:'NT$',decimalPlaces:0},{code:'JPY',name:'日圓',symbol:'¥',decimalPlaces:0}]};
const app=document.querySelector('#app'),modalRoot=document.querySelector('#modal-root');
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const preview=(value,max=50)=>{const text=String(value||'').trim().replace(/\s+/g,' ');return esc(text.length>max?text.slice(0,max)+'...':text)};
const currency=code=>S.trip?.currencies.find(c=>c.code===code)||{code,symbol:code,decimalPlaces:0};
const money=(amount,code)=>`${currency(code).symbol}${Number(amount).toLocaleString('zh-TW',{minimumFractionDigits:currency(code).decimalPlaces,maximumFractionDigits:currency(code).decimalPlaces})}`;
function toast(message){if(/正在背景(?:同步|上傳|更新)/.test(String(message)))return;const el=document.querySelector('#toast');el.textContent=message;el.hidden=false;clearTimeout(el.timer);el.timer=setTimeout(()=>el.hidden=true,2600)}
async function api(action,payload={},get=false){
  if(!API)throw new Error('尚未設定 Apps Script API URL');
  let url=API,options={method:'POST',body:JSON.stringify({action,...payload})};
  if(get){const parameters=new URLSearchParams({action,...payload,_:String(Date.now())});url=`${API}?${parameters}`;options={cache:'no-store'}}
  const response=await fetch(url,options);
  if(!response.ok)throw new Error(`API 暫時無法讀取（HTTP ${response.status}）`);
  const text=await response.text();
  let json;
  try{json=JSON.parse(text)}catch{throw new Error('API 回傳格式錯誤，請確認 Apps Script 已部署最新版本')}
  if(!json.success)throw new Error(json.error||'操作失敗');
  return json.data;
}
function recent(){try{return JSON.parse(localStorage.getItem('travel_recent')||'[]')}catch{return[]}}
function remember(){const list=recent().filter(x=>x.code!==S.trip.code);list.unshift({code:S.trip.code,name:S.trip.name});localStorage.setItem('travel_recent',JSON.stringify(list.slice(0,5)))}
function cacheTrip(){if(!S.trip)return;try{localStorage.setItem(`travel_trip_${S.trip.code}`,JSON.stringify(S.trip))}catch{}}
function taipeiParts(value){const date=new Date(value);if(Number.isNaN(date.getTime()))return null;return Object.fromEntries(new Intl.DateTimeFormat('en-US',{timeZone:'Asia/Taipei',year:'numeric',month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit',hourCycle:'h23'}).formatToParts(date).map(part=>[part.type,part.value]))}
function normalizedDate(value){const parts=String(value||'').includes('T')?taipeiParts(value):null;return parts?`${parts.year}-${parts.month}-${parts.day}`:value}
function formatTripDate(value,dates){const parts=String(value||'').split('-'),crossYear=new Set((dates||[]).map(date=>String(date).slice(0,4))).size>1;return parts.length===3?(crossYear?`${parts[0]}/${parts[1]}/${parts[2]}`:`${parts[1]}/${parts[2]}`):value}
function inclusiveDates(start,end){if(!/^\d{4}-\d{2}-\d{2}$/.test(start)||!/^\d{4}-\d{2}-\d{2}$/.test(end))throw new Error('請選擇開始與結束日期');const first=new Date(`${start}T00:00:00Z`),last=new Date(`${end}T00:00:00Z`);if(last<first)throw new Error('結束日期不可早於開始日期');const result=[];for(let cursor=new Date(first);cursor<=last;cursor.setUTCDate(cursor.getUTCDate()+1)){if(result.length>=400)throw new Error('一次最多建立 400 天');result.push(cursor.toISOString().slice(0,10))}return result}
function normalizeTrip(trip){if(!trip)return null;const validCard=item=>item&&String(item.id??'').trim()&&String(item.title??'').trim();trip.rouletteEnabled=trip.rouletteEnabled===true||String(trip.rouletteEnabled).toLowerCase()==='true';trip.wishlist=(trip.wishlist||[]).filter(validCard).map(item=>{const links=Array.isArray(item.links)&&item.links.length?item.links:(item.linkUrl?[{url:item.linkUrl,label:item.linkLabel||'開啟連結'}]:[]),legacyImages=item.imageUrl?[item.imageUrl]:[],imageUrls=[...new Set((Array.isArray(item.imageUrls)&&item.imageUrls.length?item.imageUrls:legacyImages).map(String).filter(Boolean))];return{...item,id:String(item.id),imageUrl:imageUrls[0]||'',imageUrls,links:links.filter(link=>link?.url).map(link=>({url:String(link.url),label:String(link.label||'開啟連結')}))}});trip.itinerary=(trip.itinerary||[]).filter(validCard).map(item=>{const timeParts=String(item.time||'').includes('T')?taipeiParts(item.time):null;return{...item,id:String(item.id),date:normalizedDate(item.date),time:timeParts?`${timeParts.hour}:${timeParts.minute}`:item.time}});trip.expenses=(trip.expenses||[]).filter(validCard).map(item=>({...item,id:String(item.id),date:normalizedDate(item.date)||normalizedDate(item.updatedAt),prepayments:Array.isArray(item.prepayments)?item.prepayments.filter(row=>row&&row.member&&Number(row.amount)>0).map(row=>({member:String(row.member),amount:Number(row.amount)})):[]}));trip.dates=[...new Set([...(Array.isArray(trip.dates)?trip.dates:[]),...trip.itinerary.map(item=>item.date)])].filter(Boolean).sort();return trip}
function newClientId(){return globalThis.crypto?.randomUUID?.()||`web-${Date.now()}-${Math.random().toString(36).slice(2)}`}
function cachedTrip(code){try{return normalizeTrip(JSON.parse(localStorage.getItem(`travel_trip_${code}`)||'null'))}catch{return null}}
function go(code){const url=new URL(location.href);code?url.searchParams.set('id',code):url.searchParams.delete('id');history.pushState({},'',url);if((code||null)!==S.code){S.itineraryDate='';S.itineraryQuery='';S.expenseQuery=''}S.code=code||null;if(code)loadTrip(code);else{S.page='home';S.trip=null;render()}}
async function loadTrip(code){const cached=cachedTrip(code);S.page='activity';S.user=localStorage.getItem(`travel_user_${code}`)||'';if(cached){S.trip=cached;render()}else renderLoading();try{S.trip=normalizeTrip(await api('getTrip',{code,refresh:'1'},true));cacheTrip();remember();render()}catch(e){if(cached)toast('目前顯示上次資料，背景同步失敗：'+e.message);else{toast(e.message);go(null)}}}
function renderLoading(){app.innerHTML='<div class="shell empty">✈️<br>載入旅程中…</div>'}
function render(){app.innerHTML=S.page==='home'?home():S.page==='create'?createPage():activity();bind()}
function home(){const cards=recent().map(x=>`<button class="recent-card" data-open="${esc(x.code)}"><span><b>${esc(x.name)}</b><span class="meta" style="display:block">代碼：${esc(x.code)}</span></span><span>→</span></button>`).join('');return `<div class="shell"><section class="hero"><div class="hero-icon">✈️</div><h1>一起旅行</h1><div class="subtle">慾望清單 ✦ 行程 ✦ 記帳 ✦ 結算</div></section><button id="create" class="primary full">＋ 建立新旅程</button><p class="subtle" style="text-align:center">或加入現有旅程</p><div class="join-row"><input id="join-code" class="input" placeholder="輸入活動代碼"><button id="join" class="primary">加入</button></div>${cards?`<h2 class="section-title">近期瀏覽過的旅程</h2><div class="recent">${cards}</div>`:''}</div>`}
function createPage(){return `<div class="shell"><button id="back" class="secondary">← 返回</button><h1>建立旅程</h1><div class="stack"><div class="field"><label>旅程名稱</label><input id="trip-name" class="input" placeholder="例如：雨晴海岸六日遊"></div><div class="field"><label>自訂代碼（可留空）</label><input id="trip-code" class="input" maxlength="24"></div><div class="field"><label>成員名單 *</label><div class="member-entry-row"><input id="member-input" class="input" placeholder="輸入名字，按 Enter 新增"><button id="add-member" type="button" class="secondary">新增</button></div><div id="member-list" class="member-chips">${memberChips()}</div></div><label class="feature-toggle"><input id="roulette-enabled" type="checkbox"><span class="toggle-control"></span><span><b>啟用活動轉盤</b><small>以相同機率隨機抽出一位旅程成員</small></span></label><div><div class="toolbar"><b>使用幣別</b><button id="add-currency" class="secondary">＋ 幣別</button></div><div id="currencies">${currencyRows()}</div>${currencyDatalists()}</div><button id="submit-trip" class="primary full">建立旅程</button></div></div>`}
function memberChips(){return S.draftMembers.map((name,index)=>`<span class="member-chip">${esc(name)}<button type="button" class="remove-member" data-i="${index}" aria-label="移除 ${esc(name)}">×</button></span>`).join('')}
function currencyRows(){return S.draftCurrencies.map((c,i)=>`<div class="currency-row"><input class="input c-code" data-i="${i}" list="currency-code-options" value="${esc(c.code)}" placeholder="幣別代碼"><input class="input c-name" data-i="${i}" list="currency-name-options" value="${esc(c.name)}" placeholder="幣別名稱"><input class="input c-symbol" data-i="${i}" value="${esc(c.symbol)}" placeholder="符號"><button class="danger remove-currency" data-i="${i}">×</button></div>`).join('')}
function currencyDatalists(){return `<datalist id="currency-code-options">${CURRENCY_CATALOG.map(c=>`<option value="${c.code}">${esc(c.name)}</option>`).join('')}</datalist><datalist id="currency-name-options">${CURRENCY_CATALOG.map(c=>`<option value="${esc(c.name)}">${c.code}</option>`).join('')}</datalist>`}
function activity(){if(!S.trip)return '<div class="shell empty">載入中…</div>';const tabs=[['wishlist','♡ 慾望'],['itinerary','▣ 行程'],['expenses','₿ 記帳'],['settlement','⇄ 結算']];return `<div class="shell"><header class="header"><div class="title-row"><div><div class="trip-title-line"><h1>${esc(S.trip.name)}</h1><button id="share" type="button" class="plain-icon-button share-link-button" title="複製分享連結" aria-label="複製分享連結"><svg viewBox="0 0 24 24" aria-hidden="true"><path d="M10.6 13.4a4 4 0 0 0 5.7.1l2.1-2.1a4 4 0 0 0-5.7-5.7l-1.2 1.2M13.4 10.6a4 4 0 0 0-5.7-.1l-2.1 2.1a4 4 0 0 0 5.7 5.7l1.2-1.2"/></svg></button></div><div class="meta">代碼：${esc(S.trip.code)}</div></div></div><select id="member" class="input member-select"><option value="">請選擇你的名字</option>${S.trip.members.map(m=>`<option ${m===S.user?'selected':''}>${esc(m)}</option>`).join('')}</select><nav class="tabs">${tabs.map(([id,label])=>`<button class="tab ${S.tab===id?'active':''}" data-tab="${id}">${label}</button>`).join('')}</nav></header>${tabBody()}${S.trip.rouletteEnabled?'<button id="roulette" class="fab-roulette" title="活動轉盤" aria-label="開啟活動轉盤">🎡</button>':''}<button id="home" class="fab-home" title="回首頁">⌂</button></div>`}
function tabBody(){const content=S.tab==='wishlist'?wishlist():S.tab==='itinerary'?itinerary():S.tab==='expenses'?expenses():settlement();return `<div class="tab-panel">${content}</div>`}
function avatar(name){return `<span class="avatar" title="${esc(name)}" aria-label="建立者 ${esc(name)}">${esc(String(name||'?')[0])}</span>`}
function cardActions(type,id){return `<div class="card-actions"><button type="button" class="icon-button edit-${type}" data-id="${esc(id)}" title="編輯" aria-label="編輯">✎</button><button type="button" class="icon-button delete-${type}" data-id="${esc(id)}" title="刪除" aria-label="刪除">×</button></div>`}
function imageBadge(id,count){return `<button type="button" class="image-indicator direct-wish-image" data-image-id="${esc(id)}" title="開啟 ${count} 張照片" aria-label="開啟 ${count} 張照片"><svg viewBox="0 0 24 24" aria-hidden="true"><path d="M4 5.5h16v13H4zM7 15l3.1-3.4 2.4 2.5 1.8-1.9L18 16M8 9h.01"/></svg></button>`}
function wishlist(){const rows=S.trip.wishlist.map(i=>{const imageCount=(i.imageUrls||[]).length+Number(i._pendingImageCount||0);return `<article class="card wish-card interactive-card" data-id="${i.id}"><div class="wish-title-row">${avatar(i.createdBy)}<div class="card-title">${esc(i.title)}</div></div>${i.details?`<div class="card-preview">${preview(i.details)}</div>`:''}<div class="card-badges">${(i.links||[]).map(link=>`<a class="link-pill direct-wish-link" href="${esc(link.url)}" target="_blank" rel="noopener">${esc(link.label||'開啟連結')} ↗</a>`).join('')}${imageCount?imageBadge(i.id,imageCount):''}</div></article>`}).join('');return `<div class="toolbar"><h2>慾望清單</h2><button id="add-wish" class="secondary compact list-add-action">＋ 慾望</button></div><div id="wish-list" class="stack">${rows||'<div class="empty">把想去的地方先放進來吧</div>'}</div>`}
function searchBox(id,value,placeholder){return `<label class="live-search" for="${id}"><svg viewBox="0 0 24 24" aria-hidden="true"><circle cx="11" cy="11" r="6"></circle><path d="m16 16 4 4"></path></svg><input id="${id}" type="search" value="${esc(value)}" placeholder="${esc(placeholder)}" autocomplete="off"><span class="sr-only">${esc(placeholder)}</span></label>`}
function searchable(value){return String(value??'').toLocaleLowerCase('zh-TW')}
function planCard(item){return `<article class="card schedule-card plan-card interactive-card" data-id="${item.id}"><div class="time">${esc(item.time||'未定')}</div><div><div class="card-title">${esc(item.title)}</div>${item.location?`<div class="meta">${esc(item.location)}</div>`:''}${item.linkUrl?`<a class="link-pill direct-card-link" href="${esc(item.linkUrl)}" target="_blank" rel="noopener">開啟地圖 ↗</a>`:''}</div></article>`}
function itinerary(){const dates=[...new Set([...(S.trip.dates||[]),...S.trip.itinerary.map(item=>item.date)])].filter(Boolean).sort(),query=S.itineraryQuery.trim(),needle=searchable(query),selectedDate=dates.includes(S.itineraryDate)?S.itineraryDate:(dates[0]||'');S.itineraryDate=selectedDate;const nav=dates.map(date=>`<button class="${!query&&date===selectedDate?'active':''}" data-filter-date="${date}">${formatTripDate(date,dates)}</button>`).join(''),matches=query?S.trip.itinerary.filter(item=>searchable([item.title,item.location,item.time,item.date,formatTripDate(item.date,dates)].join(' ')).includes(needle)):S.trip.itinerary.filter(item=>item.date===selectedDate),visibleDates=query?[...new Set(matches.map(item=>item.date))].sort():selectedDate?[selectedDate]:[],groups=visibleDates.map(date=>{const cards=matches.filter(item=>item.date===date).map(planCard).join('');return `<section id="date-${date}"><div class="date-heading-row"><h3 class="date-heading">${formatTripDate(date,dates)}</h3><div class="date-actions"><button type="button" class="secondary compact add-plan-date list-add-action" data-date="${date}">＋ 行程</button></div></div><div class="stack">${cards||'<div class="empty compact-empty">這天尚未安排行程</div>'}</div></section>`}).join(''),content=query?(groups||`<div class="empty compact-empty">找不到「${esc(query)}」相關行程</div>`):(groups||'<div class="empty compact-empty">這天尚未安排行程</div>');return `<div class="toolbar search-toolbar"><div class="toolbar-title"><h2>行程表</h2><button id="manage-dates" type="button" class="plain-icon-button" title="管理旅遊日期" aria-label="管理旅遊日期"><svg viewBox="0 0 24 24" aria-hidden="true"><path d="M4 20l4.2-1 10.9-10.9a2.1 2.1 0 0 0-3-3L5.2 16 4 20zM14.7 6.5l3 3"/></svg></button></div>${searchBox('itinerary-search',query,'搜尋行程…')}</div>${dates.length?`<div class="date-nav">${nav}</div>${content}`:'<div class="empty">先新增旅遊日期，再安排行程</div>'}`}
function expenseMatches(item,needle){return searchable([item.title,item.payer,item.settlementCurrency,item.date,...(item.sharers||[]),...(item.amounts||[]).flatMap(amount=>[amount.amount,amount.currencyCode,money(amount.amount,amount.currencyCode)])].join(' ')).includes(needle)}
function expenses(){const query=S.expenseQuery.trim(),needle=searchable(query),items=query?S.trip.expenses.filter(item=>expenseMatches(item,needle)):S.trip.expenses,dates=[...new Set(items.map(item=>item.date||'未指定日期'))].sort().reverse(),calendarDates=dates.filter(date=>date!=='未指定日期'),groups=dates.map(date=>`<section><h3 class="date-heading">${date==='未指定日期'?date:formatTripDate(date,calendarDates)}</h3><div class="stack">${items.filter(item=>(item.date||'未指定日期')===date).map(item=>{const prepaid=(item.prepayments||[]).reduce((sum,row)=>sum+Number(row.amount||0),0);return `<article class="card expense-card interactive-card" data-id="${item.id}"><div class="card-title">${esc(item.title)}</div><div class="expense-card-footer"><div class="expense-summary">${esc(item.payer)} 代墊 · ${esc(item.settlementCurrency)} · 分攤 ${(item.sharers||[]).map(member=>esc(member)).join('、')}${prepaid?` · 已支付 ${money(prepaid,item.settlementCurrency)}`:''}</div><div class="amount-tags">${item.amounts.map(amount=>`<span class="amount-tag">${money(amount.amount,amount.currencyCode)}</span>`).join('')}</div></div></article>`}).join('')}</div></section>`).join('');const empty=query?`找不到「${esc(query)}」相關記帳`:'尚無記帳資料';return `<div class="toolbar search-toolbar"><h2>記帳</h2>${searchBox('expense-search',query,'搜尋品項…')}<button id="add-expense" class="secondary compact list-add-action">＋ 記帳</button></div><div class="stack">${groups||`<div class="empty">${empty}</div>`}</div>`}
function memberColor(name){let hash=0;for(const character of String(name))hash=(hash*31+character.codePointAt(0))>>>0;return `hsl(${hash%360} 68% 48%)`}
function settlement(){const groups=calculateSettlement();if(!groups.length)return `<div class="toolbar"><h2>金流結算</h2></div><div class="empty">尚未記錄任何可結算費用</div>`;const selected=groups.find(group=>group.currency.code===S.settlementCurrency)||groups[0];S.settlementCurrency=selected.currency.code;const nav=groups.map(group=>`<button class="${group.currency.code===selected.currency.code?'active':''}" data-settlement-currency="${esc(group.currency.code)}" aria-pressed="${group.currency.code===selected.currency.code}">${esc(group.currency.name)} · ${esc(group.currency.code)}</button>`).join('');return `<div class="toolbar"><h2>金流結算</h2><button id="share-settlement" class="secondary page-action">分享</button></div><div class="date-nav settlement-nav" aria-label="選擇結算幣別">${nav}</div><div class="settlement-stack">${settlementGroup(selected)}</div>`}
function settlementGroup(group){const memberRows=S.trip.members.map(member=>{const paid=group.paid[member]||0,balance=group.balance[member]||0,label=balance>0?`收回 ${money(balance,group.currency.code)}`:balance<0?`應付 ${money(-balance,group.currency.code)}`:'✓ 剛好',status=balance>0?'positive':balance<0?'negative':'neutral',width=group.total?Math.min(100,paid/group.total*100):0;return `<div class="member-summary"><span class="settlement-avatar" style="background:${memberColor(member)}">${esc(member[0])}</span><div class="member-summary-body"><div class="member-summary-line"><b>${esc(member)}</b><span>代墊 ${money(paid,group.currency.code)}</span></div><div class="balance-row"><span class="balance-track"><span style="width:${width}%"></span></span><b class="${status}">${label}</b></div></div></div>`}).join(''),transfers=group.transfers.length?group.transfers.map(transfer=>`<div class="transfer"><span><b>${esc(transfer.from)}</b> → <b>${esc(transfer.to)}</b></span><b>${money(transfer.amount,group.currency.code)}</b></div>`).join(''):'<div class="settled-message">🎉 費用已均攤，不需要額外匯款</div>',details=group.expenses.map(expense=>{const amount=expense.amounts.find(item=>item.currencyCode===group.currency.code),prepaid=(expense.prepayments||[]).reduce((sum,row)=>sum+Number(row.amount||0),0);return `<div class="expense-detail"><span>${esc(expense.title)} <small>by ${esc(expense.payer)} · ${expense.sharers.map(member=>esc(member)).join('、')} 分攤${prepaid?` · 已支付 ${money(prepaid,group.currency.code)}`:''}</small></span><b>${money(amount.amount,group.currency.code)}</b></div>`}).join('');return `<section class="settlement-currency"><div class="settlement-currency-title"><div><span>${esc(group.currency.name)}</span><b>${group.currency.code}</b></div><strong>${money(group.total,group.currency.code)}</strong></div><div class="settlement-card"><h3>💸 付款方式（最少次數）</h3>${transfers}</div><div class="settlement-card totals settlement-totals"><span>活動總支出</span><strong>${money(group.total,group.currency.code)}</strong><span>已提前支付</span><strong>${money(group.prepaidTotal,group.currency.code)}</strong><span>尚待結算金額</span><strong>${money(group.unsettledTotal,group.currency.code)}</strong>${S.user?`<span>個人總支出（${esc(S.user)}）</span><strong class="personal-total">${money(group.personalCost[S.user]||0,group.currency.code)}</strong>`:''}</div><div class="settlement-card"><h3>各人代墊明細</h3>${memberRows}</div><div class="settlement-card"><h3>📋 品項費用明細</h3>${details}</div></section>`}
function modal(title,body,saveId='modal-save'){document.body.classList.add('modal-open');modalRoot.innerHTML=`<div class="modal-backdrop"><section class="modal"><h2>${title}</h2><div class="modal-scroll">${body}</div><div class="modal-actions"><button data-close class="secondary">取消</button>${saveId?`<button id="${saveId}" class="primary">儲存</button>`:''}</div></section></div>`;modalRoot.querySelector('[data-close]').onclick=closeModal;modalRoot.querySelector('.modal-backdrop').onclick=e=>{if(e.target===e.currentTarget)closeModal()}}
function closeModal(){document.body.classList.remove('modal-open');modalRoot.innerHTML=''}
function requireUser(){if(!S.user){toast('請先選擇你的名字');return false}return true}
function displayImageUrl(url){const match=String(url||'').match(/[?&]id=([^&]+)/);return match?`https://drive.google.com/thumbnail?id=${encodeURIComponent(match[1])}&sz=w1600`:url}
function beginSave(){const button=document.querySelector('#modal-save');if(!button||button.disabled)return null;button.disabled=true;button.dataset.label=button.textContent;button.textContent='儲存中…';return button}
function endSave(button){if(button?.isConnected){button.disabled=false;button.textContent=button.dataset.label||'儲存'}}
function upsertLocal(key,item){if(!item||item.id==null||!String(item.title||'').trim())throw new Error('API 回傳的卡片資料不完整');item.id=String(item.id);const list=S.trip[key],index=list.findIndex(existing=>String(existing.id)===item.id);if(index>=0)list[index]=item;else list.push(item);if(key==='itinerary')list.sort((a,b)=>String(a.date).localeCompare(String(b.date))||String(a.time||'99:99').localeCompare(String(b.time||'99:99')));else list.sort((a,b)=>Number(a.position)-Number(b.position));cacheTrip();render()}
function bindDialogueActions(onEdit,onDelete){const actions=document.querySelector('.modal-actions');actions.insertAdjacentHTML('afterbegin','<button id="dialog-edit" type="button" class="secondary">編輯</button><button id="dialog-delete" type="button" class="danger">刪除</button>');document.querySelector('#dialog-edit').onclick=()=>{closeModal();onEdit()};document.querySelector('#dialog-delete').onclick=onDelete}
function wishDialog(item){const images=item.imageUrls||[],details=item.details?`<div class="wish-detail-text">${esc(item.details)}</div>`:'',links=(item.links||[]).map(link=>`<a class="link-pill" href="${esc(link.url)}" target="_blank" rel="noopener">${esc(link.label||'開啟連結')} ↗</a>`).join('');modal(esc(item.title),`${images.length?`<div class="detail-image-frame"><img class="detail-image" src="${esc(displayImageUrl(images[0]))}" alt="${esc(item.title)}" referrerpolicy="no-referrer">${images.length>1?`<span class="photo-total-badge">共 ${images.length} 張</span>`:''}</div>`:''}${details}<div class="detail-links compact-detail-links">${links}</div>`,null);bindDialogueActions(()=>wishForm(item),()=>deleteCard('deleteWishlist','wishlist',item.id))}
function imageDialog(urls,startIndex=0){
  const images=[...new Set((Array.isArray(urls)?urls:[]).filter(Boolean))].map(displayImageUrl);
  if(!images.length){toast('照片正在同步，請稍候');return}
  let index=Math.max(0,Math.min(Number(startIndex)||0,images.length-1));
  modal('照片',`<div id="photo-gallery" class="photo-gallery"><div id="photo-frame" class="detail-image-frame photo-lightbox-frame"><img id="gallery-image" class="detail-image" alt="慾望卡片照片" referrerpolicy="no-referrer">${images.length>1?'<button id="photo-prev" type="button" class="photo-nav photo-prev" aria-label="上一張">‹</button><button id="photo-next" type="button" class="photo-nav photo-next" aria-label="下一張">›</button>':''}</div><div id="photo-counter" class="photo-counter"></div></div>`,null);
  const image=document.querySelector('#gallery-image'),counter=document.querySelector('#photo-counter'),frame=document.querySelector('#photo-frame');
  const show=next=>{index=(next+images.length)%images.length;image.src=images[index];counter.textContent=`${index+1}/${images.length}`};
  document.querySelector('#photo-prev')?.addEventListener('click',()=>show(index-1));
  document.querySelector('#photo-next')?.addEventListener('click',()=>show(index+1));
  let touchStart=0;frame.ontouchstart=event=>{touchStart=event.changedTouches[0].clientX};frame.ontouchend=event=>{const distance=event.changedTouches[0].clientX-touchStart;if(Math.abs(distance)>40)show(index+(distance<0?1:-1))};show(index)
}
function planDetails(item){modal('行程詳情',`<div class="detail-grid"><div><span>日期</span><b>${formatTripDate(item.date,S.trip.dates)}</b></div><div><span>時間</span><b>${esc(item.time||'未定')}</b></div><div><span>行程內容</span><b>${esc(item.title)}</b></div>${item.location?`<div><span>地點</span><b>${esc(item.location)}</b></div>`:''}</div>${item.linkUrl?`<a class="link-pill" href="${esc(item.linkUrl)}" target="_blank" rel="noopener">開啟地圖 ↗</a>`:''}`,null);bindDialogueActions(()=>planDialog(item),()=>deleteCard('deleteItinerary','itinerary',item.id))}
function expenseDetails(item){const prepayments=item.prepayments||[],prepaidTotal=prepayments.reduce((sum,row)=>sum+Number(row.amount||0),0),settlementAmount=Number(item.amounts.find(amount=>amount.currencyCode===item.settlementCurrency)?.amount||0),prepaymentDetail=prepayments.length?`<div class="prepayment-detail"><h3>已提前支付</h3>${prepayments.map(row=>`<div><span>${esc(row.member)}</span><b>${money(row.amount,item.settlementCurrency)}</b></div>`).join('')}<div class="prepayment-total"><span>尚待結算金額</span><b>${money(Math.max(0,settlementAmount-prepaidTotal),item.settlementCurrency)}</b></div></div>`:'';modal('記帳詳情',`<div class="detail-grid"><div><span>日期</span><b>${formatTripDate(item.date,S.trip.expenses.map(row=>row.date))}</b></div><div><span>項目</span><b>${esc(item.title)}</b></div><div><span>代墊人</span><b>${esc(item.payer)}</b></div><div><span>結算幣別</span><b>${esc(item.settlementCurrency)}</b></div><div><span>分攤人</span><b>${(item.sharers||[]).map(member=>esc(member)).join('、')}</b></div></div><div class="amount-tags detail-amounts">${item.amounts.map(amount=>`<span class="amount-tag">${money(amount.amount,amount.currencyCode)}</span>`).join('')}</div>${prepaymentDetail}`,null);bindDialogueActions(()=>expenseDialog(item),()=>deleteCard('deleteExpense','expenses',item.id))}
function wishLinkRow(link={}){return `<div class="wish-link-row"><div class="field"><label>連結網址</label><input class="input wish-link-url" inputmode="url" placeholder="https://..." value="${esc(link.url||'')}"></div><div class="field"><label>顯示文字</label><input class="input wish-link-label" placeholder="例如：官方網站" value="${esc(link.label||'')}"></div><button type="button" class="danger remove-wish-link" aria-label="移除此連結">×</button></div>`}
function bindWishLinks(){document.querySelectorAll('.remove-wish-link').forEach(button=>button.onclick=()=>{button.closest('.wish-link-row')?.remove();if(!document.querySelector('.wish-link-row'))document.querySelector('#wish-links').innerHTML=wishLinkRow();bindWishLinks()});const add=document.querySelector('#add-wish-link');if(add)add.onclick=()=>{const list=document.querySelector('#wish-links');if(list.children.length>=10){toast('一張卡片最多 10 個連結');return}list.insertAdjacentHTML('beforeend',wishLinkRow());bindWishLinks()}}
function readWishLinks(){return [...document.querySelectorAll('.wish-link-row')].map(row=>({url:row.querySelector('.wish-link-url').value.trim(),label:row.querySelector('.wish-link-label').value.trim()})).filter(link=>link.url||link.label)}
function wishForm(item=null){
  if(!requireUser())return;
  const links=item?.links?.length?item.links:[{url:item?.linkUrl||'',label:item?.linkLabel||''}],images=item?.imageUrls||[];
  const existingPhotos=images.length?`<div class="existing-photo-list">${images.map((url,index)=>`<label class="existing-photo-option"><input type="checkbox" name="keep-image" value="${esc(url)}" checked><img src="${esc(displayImageUrl(url))}" alt="照片 ${index+1}" referrerpolicy="no-referrer"><span>保留照片 ${index+1}</span></label>`).join('')}</div>`:'';
  modal(item?'編輯慾望':'新增慾望',`<div class="modal-grid"><div class="field"><label>標題</label><input id="w-title" class="input" placeholder="例如：金澤兼六園" value="${esc(item?.title||'')}"></div><div class="field"><label>詳細內容</label><textarea id="w-details" class="input" placeholder="例如營業時間、交通方式或備註">${esc(item?.details||'')}</textarea></div><div class="field"><div class="field-title-row"><label>相關連結</label><button id="add-wish-link" type="button" class="secondary small-action">＋ 連結</button></div><div id="wish-links" class="wish-links-editor">${links.map(wishLinkRow).join('')}</div></div><div class="field"><label>照片（可一次選取多張，最多 10 張）</label>${existingPhotos}<input id="w-images" type="file" accept="image/*" multiple></div></div>`);
  bindWishLinks();document.querySelector('#modal-save').onclick=()=>saveWish(item)
}
async function saveWish(existing=null){
  const button=beginSave();if(!button)return;
  const files=[...(document.querySelector('#w-images')?.files||[])],imageUrls=[...document.querySelectorAll('[name=keep-image]:checked')].map(input=>input.value),title=v('w-title').trim(),details=v('w-details'),links=readWishLinks();
  if(!title){toast('請輸入標題');endSave(button);return}
  if(links.some(link=>link.label&&!link.url)){toast('請填寫連結網址');endSave(button);return}
  if(imageUrls.length+files.length>10){toast('一張慾望卡最多可放 10 張照片');endSave(button);return}
  const firstLink=links[0]||{},tripCode=S.code,actor=S.user,backup=[...S.trip.wishlist],id=String(existing?.id||newClientId()),syncToken=newClientId(),draft={...existing,id,title,details,links,linkUrl:firstLink.url||'',linkLabel:firstLink.label||'',imageUrl:imageUrls[0]||'',imageUrls,createdBy:existing?.createdBy||actor,position:existing?.position??S.trip.wishlist.length,updatedAt:new Date().toISOString(),_pendingImageCount:files.length,_syncToken:syncToken};
  closeModal();upsertLocal('wishlist',draft);toast(files.length?'卡片已更新，照片正在背景上傳':'卡片已更新，正在背景同步');
  try{
    const imageDataUrls=await Promise.all(files.map(optimizedImageData));
    const item=await api('saveWishlist',{code:tripCode,id,mode:existing?'update':'create',title,details,links,linkUrl:firstLink.url||'',linkLabel:firstLink.label||'',imageUrls,imageDataUrls,createdBy:actor});
    if(S.code!==tripCode||!S.trip)return;
    const current=S.trip.wishlist.find(card=>String(card.id)===id);if(current?._syncToken===syncToken){upsertLocal('wishlist',item);toast('已完成同步')}
  }catch(e){
    if(S.code===tripCode&&S.trip){const current=S.trip.wishlist.find(card=>String(card.id)===id);if(current?._syncToken===syncToken){S.trip.wishlist=backup;cacheTrip();render()}}
    toast('同步失敗：'+e.message)
  }
}
function planDialog(item=null,date=''){if(!requireUser())return;const selectedDate=item?.date||date;modal(item?'編輯行程':'新增行程',`<div class="modal-grid"><div class="field"><label>日期</label><input id="p-date" type="date" class="input" value="${esc(selectedDate)}"></div><div class="field"><label>時間</label><input id="p-time" type="time" class="input" value="${esc(item?.time||'')}"></div><div class="field"><label>行程內容</label><input id="p-title" class="input" placeholder="例如：航班 IT602 出發" value="${esc(item?.title||'')}"></div><div class="field"><label>地點</label><input id="p-location" class="input" placeholder="例如：桃園國際機場 Terminal 1" value="${esc(item?.location||'')}"></div><div class="field"><label>地圖連結（選填）</label><input id="p-url" class="input" inputmode="url" placeholder="https://..." value="${esc(item?.linkUrl||'')}"></div></div>`);document.querySelector('#modal-save').onclick=()=>savePlan(item)}
function planShareUrl(code,date){const url=new URL(location.href);url.search='';url.hash='';url.searchParams.set('id',code);url.searchParams.set('tab','itinerary');url.searchParams.set('date',date);return url.toString()}
function planShareMessage(plan,{actor,tripName,tripCode,mode}){const action=mode==='update'?'更新':'新增',when=[plan.date,plan.time].filter(Boolean).join(' '),lines=[`📅 ${actor||'旅伴'} ${action}了一筆行程`,`【${tripName}】`,`${when}　${plan.title}`];if(plan.location)lines.push(`📍 ${plan.location}`);lines.push(`查看完整行程：${planShareUrl(tripCode,plan.date)}`);return lines.join('\n')}
function showPlanShareDialog(plan,context){const isUpdate=context.mode==='update',when=[formatTripDate(plan.date,S.trip?.dates||[plan.date]),plan.time].filter(Boolean).join(' ');modal(isUpdate?'行程已更新':'行程已新增',`<div class="share-plan-summary"><div class="share-plan-success" aria-hidden="true">✓</div><div><b>${esc(plan.title)}</b><div class="meta">${esc(when)}</div>${plan.location?`<div class="meta">📍 ${esc(plan.location)}</div>`:''}</div></div><p class="subtle share-plan-hint">要以你的私人 LINE 帳號分享給親友群組嗎？</p>`,null);const actions=document.querySelector('.modal-actions'),closeButton=actions?.querySelector('[data-close]');if(closeButton)closeButton.textContent='稍後';actions?.insertAdjacentHTML('beforeend','<button id="share-plan-line" type="button" class="primary line-share-button"><svg viewBox="0 0 24 24" aria-hidden="true"><path d="M20 11.2c0 4-3.6 7.2-8 7.2-.7 0-1.4-.1-2.1-.3L6 20l1-3.1c-1.9-1.3-3-3.4-3-5.7C4 7.2 7.6 4 12 4s8 3.2 8 7.2Z"/></svg><span>分享到 LINE</span></button>');document.querySelector('#share-plan-line')?.addEventListener('click',()=>{const shareUrl=`https://line.me/R/share?text=${encodeURIComponent(planShareMessage(plan,context))}`;closeModal();location.href=shareUrl})}
async function savePlan(existing=null){const button=beginSave();if(!button)return;const date=v('p-date'),time=v('p-time'),title=v('p-title').trim(),locationText=v('p-location').trim(),linkUrl=v('p-url').trim();if(!/^\d{4}-\d{2}-\d{2}$/.test(date)){toast('請選擇日期');endSave(button);return}if(!title){toast('請輸入行程內容');endSave(button);return}if(linkUrl&&!/^https?:\/\//i.test(linkUrl)){toast('連結必須以 http:// 或 https:// 開頭');endSave(button);return}const tripCode=S.code,shareContext={actor:S.user,tripName:S.trip.name,tripCode,mode:existing?'update':'create'},backupItinerary=[...S.trip.itinerary],backupDates=[...S.trip.dates],id=String(existing?.id||newClientId()),syncToken=newClientId(),draft={...existing,id,date,time,title,location:locationText,linkUrl,updatedAt:new Date().toISOString(),_syncToken:syncToken};if(!S.trip.dates.includes(date))S.trip.dates.push(date);S.trip.dates.sort();S.itineraryDate=date;closeModal();upsertLocal('itinerary',draft);toast('行程已更新，正在背景同步');try{const saved=await api('saveItinerary',{code:tripCode,id,mode:existing?'update':'create',date,time,title,location:locationText,linkUrl});if(S.code!==tripCode||!S.trip)return;const current=S.trip.itinerary.find(row=>String(row.id)===id);if(current?._syncToken===syncToken){upsertLocal('itinerary',saved);showPlanShareDialog(saved,shareContext)}}catch(e){if(S.code===tripCode&&S.trip){const current=S.trip.itinerary.find(row=>String(row.id)===id);if(current?._syncToken===syncToken){S.trip.itinerary=backupItinerary;S.trip.dates=backupDates;S.itineraryDate=existing?.date||backupDates[0]||'';cacheTrip();render()}}toast('同步失敗：'+e.message)}}
function dateManagerDialog(){if(!requireUser())return;const dates=[...(S.trip.dates||[])].sort(),rows=dates.map(date=>`<div class="date-manager-row"><span>${formatTripDate(date,dates)}</span><button type="button" class="icon-button delete-managed-date" data-date="${date}" title="刪除此日期" aria-label="刪除 ${formatTripDate(date,dates)}">×</button></div>`).join('');modal('管理旅遊日期',`<div class="modal-grid"><div class="field"><label>目前日期</label><div class="date-manager-list">${rows||'<div class="subtle">尚未建立旅遊日期</div>'}</div></div><div class="field"><label>新增日期區間</label><div class="modal-grid date-range-fields"><div class="field"><label>開始日期</label><input id="trip-date-start" type="date" class="input"></div><div class="field"><label>結束日期</label><input id="trip-date-end" type="date" class="input"></div></div></div></div>`);const start=document.querySelector('#trip-date-start'),end=document.querySelector('#trip-date-end'),save=document.querySelector('#modal-save');save.textContent='新增日期';start.onchange=()=>{end.min=start.value;if(!end.value||end.value<start.value)end.value=start.value};save.onclick=()=>saveTripDateRange();document.querySelectorAll('.delete-managed-date').forEach(button=>button.onclick=()=>deleteTripDate(button.dataset.date,true))}
async function saveTripDateRange(){const button=beginSave();if(!button)return;let added;try{added=inclusiveDates(v('trip-date-start'),v('trip-date-end'))}catch(e){toast(e.message);endSave(button);return}const tripCode=S.code,previous=[...S.trip.dates],dates=[...new Set([...(S.trip.dates||[]),...added])].sort();S.trip.dates=dates;S.itineraryDate=added[0];cacheTrip();closeModal();render();toast('日期已新增，正在背景同步');try{const saved=await api('saveTripDates',{code:tripCode,dates});if(S.code===tripCode&&S.trip){S.trip.dates=saved;cacheTrip();render();toast('已完成同步')}}catch(e){if(S.code===tripCode&&S.trip){S.trip.dates=previous;S.itineraryDate=previous[0]||'';cacheTrip();render()}toast('同步失敗：'+e.message)}}
async function deleteTripDate(date,fromManager=false){if(!requireUser())return;const count=S.trip.itinerary.filter(item=>item.date===date).length,message=count?`確定刪除 ${formatTripDate(date,S.trip.dates)} 嗎？當天的 ${count} 筆行程也會一併刪除。`:`確定刪除 ${formatTripDate(date,S.trip.dates)} 嗎？`;if(!confirm(message))return;if(fromManager)closeModal();const previousDates=[...S.trip.dates],previousItinerary=[...S.trip.itinerary];S.trip.dates=S.trip.dates.filter(item=>item!==date);S.trip.itinerary=S.trip.itinerary.filter(item=>item.date!==date);S.itineraryDate=S.trip.dates[0]||'';cacheTrip();render();try{const result=await api('deleteTripDate',{code:S.code,date});S.trip.dates=result.dates;cacheTrip();render();toast('日期已刪除')}catch(e){S.trip.dates=previousDates;S.trip.itinerary=previousItinerary;S.itineraryDate=date;cacheTrip();render();toast('刪除失敗：'+e.message)}}
function prepaymentRows(item){const values=Object.fromEntries((item?.prepayments||[]).map(row=>[row.member,row.amount]));return S.trip.members.map(member=>`<div class="prepayment-row" data-member="${esc(member)}"><span>${esc(member)}</span><div class="prepayment-input-wrap"><span class="prepayment-currency">${esc(item?.settlementCurrency||S.trip.currencies[0]?.code||'')}</span><input class="input prepayment-amount" type="number" min="0" inputmode="decimal" data-member="${esc(member)}" value="${esc(values[member]??'')}" placeholder="0"></div></div>`).join('')}
function syncPrepaymentForm(){const section=document.querySelector('#prepayment-section'),enabled=v('e-settlement-mode')==='prepaid',selected=new Set([...document.querySelectorAll('[name=sharer]:checked')].map(input=>input.value)),currencyCode=v('e-currency');if(section)section.hidden=!enabled;document.querySelectorAll('.prepayment-row').forEach(row=>{const active=selected.has(row.dataset.member);row.hidden=!active;row.querySelector('input').disabled=!enabled||!active});document.querySelectorAll('.prepayment-currency').forEach(label=>label.textContent=currencyCode);updatePrepaymentSummary()}
function updatePrepaymentSummary(){const summary=document.querySelector('#prepayment-summary');if(!summary)return;const code=v('e-currency'),settlementInput=[...document.querySelectorAll('.expense-amount')].find(input=>input.dataset.code===code),total=Number(settlementInput?.value||0),prepaid=[...document.querySelectorAll('.prepayment-amount:not(:disabled)')].reduce((sum,input)=>sum+Number(input.value||0),0);summary.innerHTML=`<span>已支付 ${money(prepaid,code)}</span><b>尚待結算 ${money(Math.max(0,total-prepaid),code)}</b>`}
function expenseDialog(item=null){if(!requireUser())return;const today=taipeiParts(new Date()),selectedSharers=item?.sharers||S.trip.members,hasPrepayments=Boolean(item?.prepayments?.length),amounts=S.trip.currencies.map(currencyItem=>{const current=item?.amounts?.find(amount=>amount.currencyCode===currencyItem.code)?.amount??'';return `<div class="field"><label>${esc(currencyItem.name)} (${currencyItem.code})</label><input class="input expense-amount" type="number" min="0" step="${currencyItem.decimalPlaces?'.01':'1'}" inputmode="decimal" data-code="${currencyItem.code}" value="${esc(current)}"></div>`}).join('');modal(item?'編輯記帳':'新增記帳',`<div class="modal-grid"><div class="field"><label>日期</label><input id="e-date" type="date" class="input" value="${esc(item?.date||`${today.year}-${today.month}-${today.day}`)}"></div><div class="field"><label>項目名稱</label><input id="e-title" class="input" placeholder="例如：機票" value="${esc(item?.title||'')}"></div><div class="field"><label>代墊人</label><select id="e-payer" class="input">${S.trip.members.map(member=>`<option ${member===(item?.payer||S.user)?'selected':''}>${esc(member)}</option>`).join('')}</select></div><div class="field"><label>分攤人</label><div class="check-grid">${S.trip.members.map(member=>`<label class="check-chip"><input type="checkbox" name="sharer" value="${esc(member)}" ${selectedSharers.includes(member)?'checked':''}><span>${esc(member)}</span></label>`).join('')}</div></div><div class="expense-amount-grid">${amounts}</div><div class="field"><label>結算幣別（只填一種金額時自動選擇）</label><select id="e-currency" class="input">${S.trip.currencies.map(currencyItem=>`<option value="${currencyItem.code}" ${currencyItem.code===item?.settlementCurrency?'selected':''}>${esc(currencyItem.name)}</option>`).join('')}</select></div><div class="field"><label>結算處理</label><select id="e-settlement-mode" class="input"><option value="included" ${hasPrepayments?'':'selected'}>全部須計入結算</option><option value="prepaid" ${hasPrepayments?'selected':''}>已有部分或全部款項支付</option></select></div><section id="prepayment-section" class="prepayment-panel" ${hasPrepayments?'':'hidden'}><div><b>各分攤人已支付金額</b><p>填寫已匯給代墊人的金額；個人總支出仍以完整費用計算。</p></div><div class="prepayment-list">${prepaymentRows(item)}</div><div id="prepayment-summary" class="prepayment-summary"></div></section></div>`);document.querySelector('#modal-save').onclick=()=>saveExpense(item);document.querySelector('#e-settlement-mode').onchange=syncPrepaymentForm;document.querySelector('#e-currency').onchange=syncPrepaymentForm;document.querySelectorAll('[name=sharer]').forEach(input=>input.onchange=syncPrepaymentForm);document.querySelectorAll('.expense-amount,.prepayment-amount').forEach(input=>input.oninput=updatePrepaymentSummary);syncPrepaymentForm()}
async function saveExpense(existing=null){const button=beginSave();if(!button)return;const date=v('e-date'),title=v('e-title').trim(),payer=v('e-payer'),amounts=[...document.querySelectorAll('.expense-amount')].filter(input=>input.value!=='').map(input=>({currencyCode:input.dataset.code,amount:Number(input.value)})),sharers=[...document.querySelectorAll('[name=sharer]:checked')].map(input=>input.value),settlementCurrency=amounts.length===1?amounts[0]?.currencyCode:v('e-currency'),prepayments=v('e-settlement-mode')==='prepaid'?[...document.querySelectorAll('.prepayment-amount:not(:disabled)')].filter(input=>input.value!==''&&Number(input.value)!==0).map(input=>({member:input.dataset.member,amount:Number(input.value)})):[];if(!title){toast('請輸入記帳名稱');endSave(button);return}if(!amounts.length||amounts.some(amount=>!Number.isFinite(amount.amount)||amount.amount<=0)){toast('請正確填寫至少一筆幣別金額');endSave(button);return}if(!sharers.length){toast('至少選擇一位分攤人');endSave(button);return}const settlementAmount=amounts.find(amount=>amount.currencyCode===settlementCurrency)?.amount;if(!settlementAmount){toast('必須填寫所選結算幣別的金額');endSave(button);return}if(prepayments.some(row=>!Number.isFinite(row.amount)||row.amount<0)||prepayments.reduce((sum,row)=>sum+row.amount,0)>settlementAmount+1e-8){toast('已支付總額不可超過此筆費用');endSave(button);return}const tripCode=S.code,actor=S.user,backup=[...S.trip.expenses],id=String(existing?.id||newClientId()),syncToken=newClientId(),draft={...existing,id,date,title,payer,settlementCurrency,amounts,sharers,prepayments,createdBy:existing?.createdBy||actor,position:existing?.position??S.trip.expenses.length,updatedAt:new Date().toISOString(),_syncToken:syncToken};closeModal();upsertLocal('expenses',draft);toast('記帳已更新，正在背景同步');try{const item=await api('saveExpense',{code:tripCode,id,mode:existing?'update':'create',date,title,payer,settlementCurrency,amounts,sharers,prepayments,createdBy:actor});if(S.code!==tripCode||!S.trip)return;const current=S.trip.expenses.find(row=>String(row.id)===id);if(current?._syncToken===syncToken){upsertLocal('expenses',item);toast('已完成同步')}}catch(e){if(S.code===tripCode&&S.trip){const current=S.trip.expenses.find(row=>String(row.id)===id);if(current?._syncToken===syncToken){S.trip.expenses=backup;cacheTrip();render()}}toast('同步失敗：'+e.message)}}
async function deleteCard(action,key,id){if(!requireUser()||!confirm('確定要刪除這張卡片嗎？'))return;closeModal();const backup=[...S.trip[key]];S.trip[key]=S.trip[key].filter(item=>String(item.id)!==String(id));cacheTrip();render();try{await api(action,{code:S.code,id});toast('已刪除')}catch(e){S.trip[key]=backup;cacheTrip();render();toast('刪除失敗：'+e.message)}}
function calculateSettlement(){return S.trip.currencies.map(selectedCurrency=>{const selected=S.trip.expenses.filter(expense=>expense.settlementCurrency===selectedCurrency.code&&expense.amounts.some(amount=>amount.currencyCode===selectedCurrency.code));if(!selected.length)return null;const factor=10**selectedCurrency.decimalPlaces,paid=Object.fromEntries(S.trip.members.map(member=>[member,0])),balance=Object.fromEntries(S.trip.members.map(member=>[member,0])),personalCost=Object.fromEntries(S.trip.members.map(member=>[member,0]));let totalMinor=0,prepaidMinor=0;selected.forEach(expense=>{const selectedAmount=expense.amounts.find(amount=>amount.currencyCode===selectedCurrency.code),amount=Math.round(Number(selectedAmount.amount)*factor);paid[expense.payer]=(paid[expense.payer]||0)+amount;balance[expense.payer]=(balance[expense.payer]||0)+amount;totalMinor+=amount;const base=Math.floor(amount/expense.sharers.length),remainder=amount%expense.sharers.length;expense.sharers.forEach((member,index)=>{const share=base+(index<remainder?1:0);balance[member]=(balance[member]||0)-share;personalCost[member]=(personalCost[member]||0)+share});(expense.prepayments||[]).forEach(row=>{const prepaid=Math.round(Number(row.amount||0)*factor);if(!prepaid||!Object.prototype.hasOwnProperty.call(balance,row.member))return;balance[expense.payer]-=prepaid;balance[row.member]+=prepaid;prepaidMinor+=prepaid})});const creditors=S.trip.members.filter(member=>balance[member]>0).map(name=>({name,amount:balance[name]})).sort((a,b)=>b.amount-a.amount),debtors=S.trip.members.filter(member=>balance[member]<0).map(name=>({name,amount:-balance[name]})).sort((a,b)=>b.amount-a.amount),transfers=[];let creditorIndex=0,debtorIndex=0;while(creditorIndex<creditors.length&&debtorIndex<debtors.length){const amount=Math.min(creditors[creditorIndex].amount,debtors[debtorIndex].amount);if(amount>0)transfers.push({from:debtors[debtorIndex].name,to:creditors[creditorIndex].name,amount:amount/factor});creditors[creditorIndex].amount-=amount;debtors[debtorIndex].amount-=amount;if(!creditors[creditorIndex].amount)creditorIndex+=1;if(!debtors[debtorIndex].amount)debtorIndex+=1}return{currency:selectedCurrency,total:totalMinor/factor,prepaidTotal:prepaidMinor/factor,unsettledTotal:Math.max(0,totalMinor-prepaidMinor)/factor,paid:Object.fromEntries(S.trip.members.map(member=>[member,(paid[member]||0)/factor])),balance:Object.fromEntries(S.trip.members.map(member=>[member,(balance[member]||0)/factor])),personalCost:Object.fromEntries(S.trip.members.map(member=>[member,(personalCost[member]||0)/factor])),transfers,expenses:selected}}).filter(Boolean)}
function copySettlement(){const groups=calculateSettlement();let text=`【${S.trip.name}】結算明細\n`;groups.forEach(group=>{text+=`\n${group.currency.name}（${group.currency.code}）總支出：${money(group.total,group.currency.code)}\n已提前支付：${money(group.prepaidTotal,group.currency.code)}\n尚待結算：${money(group.unsettledTotal,group.currency.code)}\n付款方式：\n`;text+=group.transfers.length?group.transfers.map(transfer=>`${transfer.from} → ${transfer.to}：${money(transfer.amount,group.currency.code)}`).join('\n'):'不需要額外付款';text+='\n'});navigator.clipboard?.writeText(text).then(()=>toast('結算內容已複製'))}
function wheelPoint(angle,r){const radians=angle*Math.PI/180;return{x:160+Math.cos(radians)*r,y:160+Math.sin(radians)*r}}
function wheelSvg(members){if(members.length===1)return `<svg viewBox="0 0 320 320" aria-label="活動轉盤"><circle cx="160" cy="160" r="142" fill="${memberColor(members[0])}"></circle><text x="160" y="166" text-anchor="middle">${esc(members[0])}</text><circle class="wheel-hub" cx="160" cy="160" r="13"></circle></svg>`;const sector=360/members.length,paths=members.map((member,index)=>{const start=-90+index*sector,end=start+sector,a=wheelPoint(start,142),b=wheelPoint(end,142),middle=wheelPoint(start+sector/2,92),large=sector>180?1:0;return `<path d="M160 160 L${a.x.toFixed(2)} ${a.y.toFixed(2)} A142 142 0 ${large} 1 ${b.x.toFixed(2)} ${b.y.toFixed(2)} Z" fill="${memberColor(member)}"></path><text x="${middle.x.toFixed(2)}" y="${(middle.y+5).toFixed(2)}" text-anchor="middle">${esc(String(member).slice(0,12))}</text>`}).join('');return `<svg viewBox="0 0 320 320" aria-label="活動轉盤">${paths}<circle class="wheel-hub" cx="160" cy="160" r="13"></circle></svg>`}
function fairRandomIndex(length){const values=new Uint32Array(1),limit=Math.floor(0x100000000/length)*length;do{crypto.getRandomValues(values)}while(values[0]>=limit);return values[0]%length}
function rouletteDialog(){const members=S.trip.members;if(!members.length)return;modal('活動轉盤',`<div class="wheel-wrap"><span class="wheel-pointer"></span><div id="wheel-disc" class="wheel-disc">${wheelSvg(members)}</div></div><div id="wheel-result" class="wheel-result">每位成員的中選機率皆為 ${(100/members.length).toFixed(members.length===1?0:1)}%</div><div class="wheel-controls"><button id="spin-wheel" type="button" class="primary">開始旋轉</button><button id="reset-wheel" type="button" class="secondary">重置</button></div>`,null);const disc=document.querySelector('#wheel-disc'),result=document.querySelector('#wheel-result'),spin=document.querySelector('#spin-wheel'),reset=document.querySelector('#reset-wheel');let rotation=0;spin.onclick=()=>{const winner=fairRandomIndex(members.length),sector=360/members.length;spin.disabled=true;result.textContent='旋轉中…';rotation+=360*8-(winner+.5)*sector-(rotation%360);disc.style.transition='transform 4s cubic-bezier(.12,.68,.18,1)';disc.style.transform=`rotate(${rotation}deg)`;disc.addEventListener('transitionend',()=>{result.innerHTML=`🎉 抽中 <strong>${esc(members[winner])}</strong>`;spin.disabled=false},{once:true})};reset.onclick=()=>{disc.style.transition='none';disc.style.transform='rotate(0deg)';rotation=0;result.textContent=`每位成員的中選機率皆為 ${(100/members.length).toFixed(members.length===1?0:1)}%`}}
function optimizedImageData(file){return new Promise((resolve,reject)=>{const reader=new FileReader();reader.onerror=reject;reader.onload=()=>{const image=new Image();image.onerror=reject;image.onload=()=>{const maximum=1280,scale=Math.min(1,maximum/Math.max(image.naturalWidth,image.naturalHeight)),canvas=document.createElement('canvas');canvas.width=Math.max(1,Math.round(image.naturalWidth*scale));canvas.height=Math.max(1,Math.round(image.naturalHeight*scale));canvas.getContext('2d').drawImage(image,0,0,canvas.width,canvas.height);resolve(canvas.toDataURL('image/jpeg',.78))};image.src=reader.result};reader.readAsDataURL(file)})}function v(id){return document.querySelector('#'+id)?.value||''}
function bind(){
  document.querySelector('#create')?.addEventListener('click',()=>{S.draftMembers=[];S.draftCurrencies=[{code:'TWD',name:'新台幣',symbol:'NT$',decimalPlaces:0},{code:'JPY',name:'日圓',symbol:'¥',decimalPlaces:0}];S.page='create';render()});
  document.querySelector('#back')?.addEventListener('click',()=>{S.page='home';render()});
  document.querySelector('#join')?.addEventListener('click',()=>go(v('join-code').trim().toUpperCase()));
  document.querySelectorAll('[data-open]').forEach(button=>button.onclick=()=>go(button.dataset.open));
  document.querySelector('#home')?.addEventListener('click',()=>go(null));
  document.querySelector('#roulette')?.addEventListener('click',rouletteDialog);
  document.querySelector('#share')?.addEventListener('click',()=>navigator.clipboard.writeText(location.href).then(()=>toast('分享連結已複製')));
  document.querySelector('#member')?.addEventListener('change',event=>{S.user=event.target.value;localStorage.setItem(`travel_user_${S.code}`,S.user);render()});
  document.querySelectorAll('[data-tab]').forEach(button=>button.onclick=()=>{S.tab=button.dataset.tab;render()});
  document.querySelector('#add-wish')?.addEventListener('click',()=>wishForm());
  document.querySelectorAll('.wish-card').forEach(card=>card.onclick=()=>wishDialog(S.trip.wishlist.find(item=>item.id===card.dataset.id)));
  document.querySelectorAll('.plan-card').forEach(card=>card.onclick=()=>planDetails(S.trip.itinerary.find(item=>item.id===card.dataset.id)));
  document.querySelectorAll('.expense-card').forEach(card=>card.onclick=()=>expenseDetails(S.trip.expenses.find(item=>item.id===card.dataset.id)));
  document.querySelectorAll('.direct-wish-image').forEach(button=>button.onclick=event=>{event.stopPropagation();const item=S.trip.wishlist.find(card=>String(card.id)===String(button.dataset.imageId));imageDialog(item?.imageUrls||[])});
  document.querySelectorAll('.direct-wish-link,.direct-card-link').forEach(link=>link.onclick=event=>event.stopPropagation());
  document.querySelector('#manage-dates')?.addEventListener('click',dateManagerDialog);
  document.querySelectorAll('.add-plan-date').forEach(button=>button.onclick=()=>planDialog(null,button.dataset.date));
  document.querySelectorAll('[data-filter-date]').forEach(button=>button.onclick=()=>{S.itineraryDate=button.dataset.filterDate;S.itineraryQuery='';render()});
  document.querySelectorAll('[data-settlement-currency]').forEach(button=>button.onclick=()=>{S.settlementCurrency=button.dataset.settlementCurrency;render()});
  document.querySelector('#add-expense')?.addEventListener('click',()=>expenseDialog());
  document.querySelector('#share-settlement')?.addEventListener('click',copySettlement);
  bindLiveSearch('itinerary-search','itineraryQuery');
  bindLiveSearch('expense-search','expenseQuery');
  bindCreate();bindSort()
}
function bindLiveSearch(id,stateKey){const input=document.querySelector('#'+id);if(!input)return;let composing=false;const apply=()=>{if(composing)return;S[stateKey]=input.value;render();requestAnimationFrame(()=>{const current=document.querySelector('#'+id);if(current){current.focus();const end=current.value.length;current.setSelectionRange?.(end,end)}})};input.addEventListener('compositionstart',()=>composing=true);input.addEventListener('compositionend',()=>{composing=false;apply()});input.addEventListener('input',event=>{if(!event.isComposing)apply()})}
function bindCreate(){const addMember=()=>{const input=document.querySelector('#member-input'),name=input?.value.trim();if(!name)return;if(S.draftMembers.includes(name)){toast('成員名稱不可重複');input.select();return}S.draftMembers.push(name);input.value='';refreshMemberChips();input.focus()};document.querySelector('#add-member')?.addEventListener('click',addMember);document.querySelector('#member-input')?.addEventListener('keydown',event=>{if(event.key==='Enter'){event.preventDefault();addMember()}});bindMemberRemove();document.querySelector('#add-currency')?.addEventListener('click',()=>{syncCurrencies();S.draftCurrencies.push({code:'',name:'',symbol:'',decimalPlaces:0});refreshCurrencyRows()});bindCurrencyRows();document.querySelector('#submit-trip')?.addEventListener('click',async()=>{syncCurrencies();try{const members=[...S.draftMembers],rouletteEnabled=Boolean(document.querySelector('#roulette-enabled')?.checked);const trip=await api('createTrip',{name:v('trip-name'),customCode:v('trip-code'),members,currencies:S.draftCurrencies,rouletteEnabled});S.user=members[0];S.code=trip.code;S.trip=trip;S.page='activity';cacheTrip();localStorage.setItem(`travel_user_${trip.code}`,S.user);const url=new URL(location.href);url.searchParams.set('id',trip.code);history.pushState({},'',url);remember();render()}catch(e){toast(e.message)}})}
function bindMemberRemove(){document.querySelectorAll('.remove-member').forEach(button=>button.onclick=()=>{S.draftMembers.splice(Number(button.dataset.i),1);refreshMemberChips()})}
function refreshMemberChips(){const list=document.querySelector('#member-list');if(list){list.innerHTML=memberChips();bindMemberRemove()}}
function bindCurrencyRows(){document.querySelectorAll('.remove-currency').forEach(button=>button.onclick=()=>{syncCurrencies();S.draftCurrencies.splice(Number(button.dataset.i),1);refreshCurrencyRows()});document.querySelectorAll('.c-code,.c-name').forEach(input=>input.addEventListener('input',autofillCurrency))}
function refreshCurrencyRows(){const list=document.querySelector('#currencies');if(list){list.innerHTML=currencyRows();bindCurrencyRows()}}
function autofillCurrency(event){const input=event.currentTarget,index=Number(input.dataset.i),value=input.value.trim();const preset=input.classList.contains('c-code')?CURRENCY_CATALOG.find(c=>c.code===value.toUpperCase()):CURRENCY_CATALOG.find(c=>c.name===value||c.aliases.includes(value));if(!preset)return;S.draftCurrencies[index]={code:preset.code,name:preset.name,symbol:preset.symbol,decimalPlaces:preset.decimalPlaces};const row=input.closest('.currency-row');row.querySelector('.c-code').value=preset.code;row.querySelector('.c-name').value=preset.name;row.querySelector('.c-symbol').value=preset.symbol}
function syncCurrencies(){document.querySelectorAll('.c-code').forEach(x=>S.draftCurrencies[x.dataset.i].code=x.value.toUpperCase());document.querySelectorAll('.c-name').forEach(x=>S.draftCurrencies[x.dataset.i].name=x.value);document.querySelectorAll('.c-symbol').forEach(x=>S.draftCurrencies[x.dataset.i].symbol=x.value)}
function bindSort(){const element=document.querySelector('#wish-list');if(!element||!window.Sortable)return;Sortable.create(element,{animation:160,delay:matchMedia('(pointer:coarse)').matches?300:0,delayOnTouchOnly:true,chosenClass:'dragging',dragClass:'dragging',ghostClass:'ghost',filter:'.icon-button',preventOnFilter:false,onEnd:async event=>{const moved=S.trip.wishlist.splice(event.oldIndex,1)[0];S.trip.wishlist.splice(event.newIndex,0,moved);S.trip.wishlist.forEach((item,index)=>item.position=index);cacheTrip();try{await api('reorderWishlist',{code:S.code,ids:S.trip.wishlist.map(item=>item.id)})}catch(error){toast(error.message);await loadTrip(S.code)}}})}
window.addEventListener('popstate',()=>{const code=new URLSearchParams(location.search).get('id');code?loadTrip(code):(S.page='home',S.trip=null,render())});
S.code?loadTrip(S.code):render();
})();
